services:
  chat:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CA_URL: ${CA_URL}
      secrets:
        - ca_token
    container_name: ds_agents_chat
    working_dir: /app
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AWS_PROFILE: ${AWS_PROFILE:-3VDEV}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}
      DS_MCP_AWS_SETUP: ${DS_MCP_AWS_SETUP:-0}
    command: python chat.py --agent ${CHAT_AGENT:-provider}
    volumes:
      - ${HOME}/.aws:/root/.aws:rw
      - ./env.sh:/app/env.sh:ro
    stdin_open: true
    tty: true

secrets:
  ca_token:
    environment: CA_TOKEN
